---
AWSTemplateFormatVersion: "2010-09-09"
Description: "The template used to create an ECS Service from the ECS Console."
Parameters: 
  ECSClusterName: 
    Type: "String"
    Default: "Test"
  ECSServiceName: 
    Type: "String"
    Default: "ff"
  SecurityGroupIDs: 
    Type: "CommaDelimitedList"
    Default: "sg-0219880a6b773a538"
  SubnetIDs: 
    Type: "CommaDelimitedList"
    Default: "subnet-00fda2dcdd5ec9fd7,subnet-0e16eec301d55bc5f,subnet-03df422db2542c9a0,subnet-013f45073df8ae2cf,subnet-0a202cb1f794f5cd2,subnet-05e30c4f08a1e67eb"
  VpcID: 
    Type: "String"
    Default: "vpc-0509bdc851d45c903"
 
Resources: 
  ECSService: 
    Type: "AWS::ECS::Service"
    Properties: 
      Cluster: "Test"
      CapacityProviderStrategy: 
      - CapacityProvider: "FARGATE"
        Base: "0"
        Weight: "1"
      TaskDefinition: "arn:aws:ecs:us-east-1:013030615903:task-definition/task-def-MyTaskDefinition-QYXzLZJghdj5:1"
      ServiceName: "ff"
      SchedulingStrategy: "REPLICA"
      DesiredCount: "1"
      NetworkConfiguration: 
        AwsvpcConfiguration: 
          AssignPublicIp: "ENABLED"
          SecurityGroups: 
            Ref: "SecurityGroupIDs"
          Subnets: 
            Ref: "SubnetIDs"
      PlatformVersion: "LATEST"
      DeploymentConfiguration: 
        MaximumPercent: "200"
        MinimumHealthyPercent: "100"
        DeploymentCircuitBreaker: 
          Enable: "true"
          Rollback: "true"
      DeploymentController: 
        Type: "ECS"
      ServiceConnectConfiguration: 
        Enabled: "false"
